### ISSUE TITLE
Enforce 'leaver percentage' in matchmaking or otherwise punish leavers

### ISSUE THREAD

**Issue by mrhappyasthma** [Project-KONGOR/Defect-Reports#32]
Perhaps we should make it so that leavers cannot re-queue for some time. Or people with a leaver percentage above the threshold cannot queue (or cannot queue for some time period).

**Comment by korDen** [comment]
I *think* leaver % is already working and I think I ever verified it by accident. But we can do better. E.g. leave unfinished game -> cannot join TMM until that game is over + 1hr.

**Comment by mrhappyasthma** [comment]
Tbh I may take it a step further. And block them from TMM for an hour or something. To really discourage it.

And if you accidentally d/ced or whatever, then too bad. Go take a short break. <too bad it's me, blacksmith>

**Comment by neutrondev03** [comment]
Totally agree with myhappyasthma we really need to discourage this but then another problem will arise. People won't leave but avoid afk or just do silly things.

**Comment by mrhappyasthma** [comment]
But we can see those in replays and are actionable offenses -- e.g. legit suspension for occurrences of intentional AFK or repeated AFK.

**Comment by mrhappyasthma** [comment]
This is fixed.
