### ISSUE TITLE
vault not working / taunts etc

### ISSUE THREAD

**Issue by superbjorn09** [Project-KONGOR/Defect-Reports#38]
you can select bought upgrades but they re not gonna be activated.
So, thats works:
![image](https://user-images.githubusercontent.com/32303582/185438831-da0252b4-a379-4d95-ba0a-a8395521a646.png)

but after that i ll get an error:
![image](https://user-images.githubusercontent.com/32303582/185438931-329725da-176c-48d0-88c0-49494cb60f0f.png)

As you can see there is a float expected (FtoA = Float to Ascii), but a string was send by the server.

**Comment by mrhappyasthma** [comment]
We deployed some changes to hopefully fix this. Can you try again and see if you're still getting Lua errors.

(also thank you for the screenshots, very helpful)

**Comment by superbjorn09** [comment]
this seems to be partially solved.
It shows a "selected" now:
![image](https://user-images.githubusercontent.com/32303582/185552885-9e33db7d-0ff6-452e-9fda-aff747b0092a.png)

But the error in the console still persists:
![image](https://user-images.githubusercontent.com/32303582/185552949-029bb5d7-418f-46e3-8577-4b1bea70ccbc.png)

**Comment by mrhappyasthma** [comment]
This error should be harmless. It appears to be a bug in the actual HoN code, but shouldn't affect anything.

If you have any issues actually seeing this Taunt in game, please let us know!

**Comment by superbjorn09** [comment]
it works now, thanks :-)
