### ISSUE TITLE
1007 - Experience and levels are different on account preview and detailed account lookup

### ISSUE THREAD

**Issue by wizzxa** [Project-KONGOR/Defect-Reports#7]
![1007-2](https://user-images.githubusercontent.com/31215706/182049606-a6b7e048-70fb-4f84-a1bb-ff157068081b.jpg)
![1007-1](https://user-images.githubusercontent.com/31215706/182049608-71c2719d-af50-437f-b6db-da474eeda1f1.jpg)

**Comment by korDen** [comment]
Fyi this is caused by Auth either not setting the level, or incorrectly setting level to 0.

**Comment by wizzxa** [comment]
Checked and closed
