### ISSUE TITLE
1008 - Hosted game servers are not discoverable from Public - Create game menu

### ISSUE THREAD

**Issue by wizzxa** [Project-KONGOR/Defect-Reports#8]
![1008](https://user-images.githubusercontent.com/31215706/182049727-e92e8e71-ca60-412f-a006-f1bc8b9b65e1.jpg)

**Comment by Xen0byte** [comment]
I think I know what is causing this one and it's on my TODO list to fix ASAP. The credentials are dynamic and they update every hour, but that also causes them to fail authentication in the current implementation. I will fix this one with the highest priority. The workaround, for now, is to restart the servers once per hour... but obviously, that is a terrible workaround.

**Comment by korDen** [comment]
This issue is most likely fixed by now.

**Comment by wizzxa** [comment]
Checked and closed
